server:
  port: 8080
  error:
    include-message: always

spring:
  main:
    web-application-type: servlet #Changes the type of web application, this one disabled the server. default = servlet
  datasource: #database configuration
    url: jdbc:postgresql://localhost:5332/customer
    username: amigoscode
    password: password
  jpa:
    hibernate:
      ddl-auto: validate #to use flyway ddl-auto has to be turned off
    properties:
      hibernate:
        format_sql: true
        show_sql: true
